import {
  acIcon,
  barbQIcon,
  bathIcon,
  chargeIcon,
  cleaningIcon,
  deskIcon,
  dispenserIcon,
  dryerIcon,
  fireAlarmIcon,
  gymIcon,
  ironIcon,
  matleIcon,
  parkingIcon,
  silencerIcon,
  smokeIcon,
  stoveIcon,
  switchIcon,
  teaIcon,
  tvIcon,
} from "../assets/aminities/amenitiesExport";

export const AMENITY_GROUPS: { title: string; items: string[] }[] = [
  {
    title: "Essentials",
    items: [
      "Wifi",
      "Air - Conditioning",
      "Heating",
      "Kitchen",
      "Washer",
      "Dryer",
      "Iron",
      "TV",
      "Hair dryer",
      "Dedicated Workspace",
    ],
  },
  {
    title: "Features",
    items: [
      "Gym",
      "EV Charger",
      "Free Parking",
      "Smoking Allowed",
      "Hot Tub",
      "BBQ Grill",
      "Breakfast",
      "Pool",
    ],
  },
  {
    title: "Safety",
    items: ["Smoke Alarm", "Carbon Monoxide Alarm", "First Aid Kit"],
  },
];

export const amenityIcons: Record<string, string> = {
  "Smoke Alarm": smokeIcon,
  "Carbon Monoxide Alarm": fireAlarmIcon,
  "First Aid Kit": cleaningIcon,
  Gym: gymIcon,
  "EV Charger": chargeIcon,
  "Free Parking": parkingIcon,
  "Smoking Allowed": silencerIcon,
  "Hot Tub": bathIcon,
  "BBQ Grill": barbQIcon,
  Breakfast: teaIcon,
  Pool: matleIcon,
  Wifi: switchIcon,
  "Air - Conditioning": acIcon,
  Heating: stoveIcon,
  Kitchen: dispenserIcon,
  Washer: cleaningIcon,
  Dryer: dryerIcon,
  Iron: ironIcon,
  TV: tvIcon,
  "Hair dryer": dryerIcon,
  "Dedicated Workspace": deskIcon,
};
