export const bedTypeOptions = [
  { label: "Full", value: "full" },
  { label: "Twin", value: "twin" },
  { label: "Twin XL", value: "twin-xl" },
  { label: "Bunk Single Top", value: "bunk-single-top" },
  { label: "Bunk Single Bottom", value: "bunk-single-bottom" },
  { label: "Bunk Double Top", value: "bunk-double-top" },
  { label: "Bunk Double Bottom", value: "bunk-double-bottom" },
  { label: "Bunk Full Top", value: "bunk-full-top" },
  { label: "Bunk Full Bottom", value: "bunk-full-bottom" },
  { label: "Bunk Twin Top", value: "bunk-twin-top" },
  { label: "Bunk Twin Bottom", value: "bunk-twin-bottom" },
  { label: "Bunk Twin XL Top", value: "bunk-twin-xl-top" },
  { label: "Bunk Twin XL Bottom", value: "bunk-twin-xl-bottom" },
];
